import Foundation

/// The local NCOM engine is the app's execution layer. Apple Foundation Models
/// is the cognitive front-end; the engine owns tools, memory, VM/file boundaries,
/// and optional expansion runtimes.
@MainActor
final class NCOMEngine: ObservableObject {
    @Published private(set) var state: State = .idle
    @Published private(set) var events: [Event] = []

    enum State: Equatable {
        case idle
        case ready
        case thinking
        case unavailable(String)
        case error(String)
    }

    struct Event: Identifiable, Equatable {
        let id = UUID()
        let timestamp: Date
        let title: String
        let detail: String
    }

    private let router = NCOMToolRouter()
    private var foundation: FoundationModelsBridge?

    init() {
        foundation = FoundationModelsBridge.make(router: router)
        state = foundation == nil ? .unavailable("Apple Foundation Models requires a supported Apple Intelligence device/OS") : .ready
    }

    func respond(to prompt: String) async -> String {
        guard !prompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return "" }
        guard let foundation else {
            state = .unavailable("Apple Foundation Models is unavailable on this device or configuration.")
            return "NCOM cannot run its Apple on-device model on this device right now. The app remains usable for local tools and configuration."
        }

        state = .thinking
        events.append(Event(timestamp: .now, title: "Foundation Model", detail: "Processing request"))
        do {
            let result = try await foundation.respond(to: prompt)
            state = .ready
            events.append(Event(timestamp: .now, title: "Response complete", detail: "Generated by Apple Foundation Models"))
            return result
        } catch {
            state = .error(error.localizedDescription)
            events.append(Event(timestamp: .now, title: "Generation error", detail: error.localizedDescription))
            return "NCOM generation failed: \(error.localizedDescription)"
        }
    }
}
